defaults: &defaults
  fields:
    - email
    - input
    - textarea
    - dropdown
    - boolean
    - radiobutton
    - checkbox
    - number
    - datetime
    - file
    - user
    - objectlink

  roles:
    - admin
    - moderator
    - user
  default_role: user

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
