defaults: &defaults
  fields:
    - text_area
    - text_input
    - text_markup

  roles:
    - admin
    - moderator
    - user
  default_role: user

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
